### ISSUE TITLE
New ICB Code Changes

### ISSUE THREAD

**Issue by CliffConway** [FarrukhAhmed82/ICB#1]
Hi Farrukh,

Just came across your SQL related to ICB codes - very useful. 

Are you aware that the ICB coding is changing in July 2019 (see link at the bottom of this page (https://www.ftserussell.com/financial-data/industry-classification-benchmark-icb ))?

Do you have any intentions of creating a new version of your SQL?

**Comment by KABALAS** [comment]
look at 
https://www.ftserussell.com/data/industry-classification-benchmark-icb
https://research.ftserussell.com/products/downloads/ICBStructure-Eng.pdf?_ga=2.232392922.494962670.1562994088-1745991472.1562994088

**Comment by FarrukhAhmed82** [comment]
Thanks CliffConway for information
